In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("C:/Users/HP/Downloads/multi_column_dataset - Copy.csv")

In [4]:
data

,Age,Salary,Experience,Hours_Worked_Per_Week,Performance_Score,Projects_Completed
0,22,25000,1,38,7,2
1,25,28000,2,40,6,3
2,27,30000,3,42,7,4
3,29,32000,4,45,8,5
4,31,35000,5,48,9,6
5,33,38000,6,50,9,7
6,35,40000,7,52,8,7
7,37,42000,8,55,9,8
8,40,45000,9,58,9,9
9,42,48000,10,60,10,10
10,45,52000,12,62,9,11
11,47,55000,13,65,10,12
12,50,60000,15,68,10,13
13,52,63000,16,70,10,14
14,55,67000,18,72,9,14
15,57,70000,20,75,9,15
16,60,75000,22,78,8,15
17,62,78000,23,80,8,16
18,65,82000,25,82,9,17
19,68,85000,27,85,9,18

In [5]:
data.head(5)

,Age,Salary,Experience,Hours_Worked_Per_Week,Performance_Score,Projects_Completed
0,22,25000,1,38,7,2
1,25,28000,2,40,6,3
2,27,30000,3,42,7,4
3,29,32000,4,45,8,5
4,31,35000,5,48,9,6

In [6]:
data.columns

Index(['Age', 'Salary', 'Experience', 'Hours_Worked_Per_Week',
       'Performance_Score', 'Projects_Completed'],
      dtype='object')

In [29]:
for i in data.columns:
    print(f"{i}")
    q1 = data[i].quantile(0.25)
    q3 = data[i].quantile(0.75)
    IQR = q3-q1
    print(f"IQR: {IQR}")
    LB = q1 - 1.5 * IQR
    UB = q3 + 1.5 * IQR
    print(f"Lower Bound: {LB}\nUpper Bound: {UB}")
    outlier = data[(data[i] < LB) | (data[i] > UB)]
    print("Outlier is:", outlier)
    print("\n")
    print("\n")

Age
IQR: 23.0
Lower Bound: -2.0
Upper Bound: 90.0
Outlier is: Empty DataFrame
Columns: [Age, Salary, Experience, Hours_Worked_Per_Week, Performance_Score, Projects_Completed]
Index: []




Salary
IQR: 30500.0
Lower Bound: -8500.0
Upper Bound: 113500.0
Outlier is: Empty DataFrame
Columns: [Age, Salary, Experience, Hours_Worked_Per_Week, Performance_Score, Projects_Completed]
Index: []




Experience
IQR: 12.75
Lower Bound: -13.375
Upper Bound: 37.625
Outlier is: Empty DataFrame
Columns: [Age, Salary, Experience, Hours_Worked_Per_Week, Performance_Score, Projects_Completed]
Index: []




Hours_Worked_Per_Week
IQR: 23.25
Lower Bound: 14.625
Upper Bound: 107.625
Outlier is: Empty DataFrame
Columns: [Age, Salary, Experience, Hours_Worked_Per_Week, Performance_Score, Projects_Completed]
Index: []




Performance_Score
IQR: 1.0
Lower Bound: 6.5
Upper Bound: 10.5
Outlier is:    Age  Salary  Experience  Hours_Worked_Per_Week  Performance_Score  \
1   25   28000           2                     40                  6

   Projects_Completed
1                   3




Projects_Completed
IQR: 7.5
Lower Bound: -4.5
Upper Bound: 25.5
Outlier is: Empty DataFrame
Columns: [Age, Salary, Experience, Hours_Worked_Per_Week, Performance_Score, Projects_Completed]
Index: []